name: Build elsa designer
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  push_to_npm:
    name: Push NPM package to NPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10
          
      - run: cd ./src/designer/elsa-workflows-studio/
      - run: npm install
      - run: npm run build
        
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          package: ./src/designer/elsa-workflows-studio/package.json
          token: ${{ secrets.NPM_TOKEN }}